### ISSUE TITLE
Lecture et écriture d'un fichier de mots-clé 

### ISSUE THREAD

**Issue by JulesBLG** [Cocolollipop/mido-svg#12]
Première utilisation des mots-clé ainsi que réorganisation du code

**Comment by Cocolollipop** [comment]
# Déroulement de l'évolution
Cf commit [d3b3e58](https://github.com/Cocolollipop/mido-svg/commit/d3b3e58e55edcf1e7ab07fec98d1324990f444ee)

1/ Ajout de la fonction setTagsList et readTagsList et createTagList dans la classe Formation
2/ Test des fonctions dans la classe LicenceSVG

### Commentaire
J'admets que faire des tests de fonction dans la classe LicenceSVG directement n'était pas très élégant. Toutefois, à ce moment là, la direction que prenait le projet n'était pas très claire pour nous.
